POST http://localhost:8080/user/register
Content-Type: application/json

{
    "fullname": "test123",
    "email": "test@gmail.com",
    "password": "test"
}

### Login
POST http://localhost:8080/user/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test"
}

###
DELETE http://localhost:8080/course/delete/1
