POST http://localhost:8080/user/login
Content-Type: application/json

{
    "email": "coba@gmail.com",
    "password": "coba123"
}

###
POST http://localhost:8080/user/register
Content-Type: application/json

{
    "fullname": "coba",
    "email": "coba@gmail.com",
    "password": "coba123"
}

###
GET http://localhost:8080/task/list